// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuY0RN-yAcnqtPx2kDC_CO3xsmSR0-RR8',
    appId: '1:33898045138:android:cec9c7e2776d1d0932970b',
    messagingSenderId: '33898045138',
    projectId: 'hadamath',
    databaseURL: 'https://hadamath-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hadamath.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO2ZuzomF1rGcrZ-ZLGNSUXhOwtgPkfUY',
    appId: '1:33898045138:ios:3e98140346e37e0332970b',
    messagingSenderId: '33898045138',
    projectId: 'hadamath',
    databaseURL: 'https://hadamath-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hadamath.appspot.com',
    iosClientId: '33898045138-2prp0gj2hsi4bo6dril8e65db5n6maf9.apps.googleusercontent.com',
    iosBundleId: 'com.bargoLoft.hadaMath',
  );
}
